baseURL = "https://asantana1970.github.io/static_website2/"
languageCode = "en-us"
title = "MISG XXI - GRUPO #7"
publishDir ="docs" 
theme = "ananke" 

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://www.instagram.com/?hl=es-la"
  youtube = "https://www.youtube.com/watch?v=CkFcRU2FPvQ"
  github = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = "/images/business_opportunitie-3.jpg"
  recent_posts_number = 2
